### ISSUE TITLE
Mock benchmarkjs in tests

### ISSUE THREAD

**Issue by Avaq** [sanctuary-js/sanctuary-benchmark#4]
Currently CI cannot complete the tests because they take too much computational power. By mocking benchmarkjs this issue can be resolved.

**Comment by Avaq** [comment]
@davidchambers It looks like this was fixed by #26 
See this old PR for comparison: https://github.com/sanctuary-js/sanctuary-benchmark/pull/2#issuecomment-374198810

**Comment by davidchambers** [comment]
Fantastic!

**Comment by Avaq** [comment]
Actually that was your volkswagen commit (ff6be5ce76a2b2511244e241809a3286cb1958ee) making me think things were working now :P
But they do actually seem to be working for real: #27 :tada:
